// مناطق البحرين — مصدر واحد لكل الأقسام ذات المواقع الفعلية.
//
// الغرض: ألا يحتاج صاحب الموقع لكتابة اسم منطقة يدوياً بلوحة التحكم. أي
// تصنيف مخصّص يُكتب يدوياً يحتاج ترجمة إنجليزية بالكود وإلا فشل النشر،
// فوجود كل المناطق جاهزة يمنع هذي المشكلة من أصلها.
//
// تُدمَج تلقائياً بـ:
//   src/_data/sections.js  -> categoryOptions لأقسام الأماكن الفعلية
//   src/_data/tags_en.js   -> قاموس الترجمة
//
// المصدر: أسماء المناطق المستخدمة بالموقع أصلاً (43) + مناطق من
// OpenStreetMap لها اسمان عربي وإنجليزي موثّقان (56).
// الأسماء الموجودة سابقاً لها الأولوية — تغييرها يكسر تصنيفات المحتوى الحالي.
module.exports = {
  "أبو بهام": "Abu Baham",
  "أبو صيبع": "Abu Saiba",
  "أبو قوة": "Abu Quwah",
  "البديع": "Al Budaiya",
  "البرهامة": "Al-Burhama",
  "البلاد القديم": "Bilad Al Qadeem",
  "الجفير": "Al-Juffair",
  "الجنبية": "Janabiyah",
  "الحجر": "Al Hajar",
  "الحد": "Al Hidd",
  "الحورة": "Al Hoora",
  "الخميس": "Al Khamis",
  "الدراز": "Al Daraz",
  "الدير": "Al Dair",
  "الديه": "Al Diyah",
  "الرفاع": "Riffa",
  "الرفاع الشرقي": "East Riffa",
  "الزلاق": "Zallaq",
  "الزنج": "Zinj",
  "السقية": "Al-Suqayya",
  "السلمانية": "Al Salmaniya",
  "السنابس": "Sanabis",
  "السهلة": "Sehla",
  "السهلة الجنوبية": "South Sehla",
  "السهلة الشمالية": "North Sehla",
  "السويفية": "Suwayfiya",
  "السيف": "Seef",
  "الشاخورة": "Shakhura",
  "الصالحية": "Salihiya",
  "العدلية": "Adliya",
  "العكر": "Al Eker",
  "الغريفة": "Al Ghurayfah",
  "الفاتح": "Al Fatih",
  "القدم": "Al Qadam",
  "القضيبية": "Al Qudaibiya",
  "القلعة": "Al Qalah",
  "الكورة": "Kawarah",
  "الماحوز": "Al Mahooz",
  "المالكية": "Malkiya",
  "المحرق": "Muharraq",
  "المدينة الشمالية": "Northern City",
  "المرخ": "Al Markh",
  "المُصلى": "Al Musalla",
  "المعامير": "Ma'ameer",
  "المقشع": "Al Maqsha",
  "المنامة": "Manama",
  "المنطقة التعليمية": "Education Zone",
  "المنطقة الدبلوماسية": "Diplomatic Area",
  "النويدرات": "Nuwaidrat",
  "الهملة": "Hamala",
  "أم الحصم": "Umm Al Hassam",
  "بسيتين": "Busaiteen",
  "بني جمرة": "Bani Jamra",
  "بوري": "Buri",
  "بوعشيرة": "Bu Ashira",
  "بوغزال": "Bu Ghazal",
  "توبلي": "Tubli",
  "جبلة حبشي": "Jeblat Hebshi",
  "جد الحاج": "Jid Al-Haj",
  "جد علي": "Jid Ali",
  "جدحفص": "Jidhafs",
  "جدعلي": "Jid Ali",
  "جرداب": "Jurdab",
  "جزر أمواج": "Amwaj Islands",
  "جنوسان": "Janusan",
  "جو": "Jaww",
  "حالة السلطة": "Halat Al-Sletah",
  "حلة عبد الصالح": "Hillat Abdul Saleh",
  "دار كليب": "Dar Kulayb",
  "دلمونيا": "Dilmunia",
  "دمستان": "Dumistan",
  "ديار المنامة": "Diyar Al Manama",
  "راس رمان": "Ras Rumman",
  "سار": "Sar",
  "سترة": "Sitra",
  "سفالة": "Sufala",
  "سلماباد": "Salmabad",
  "سماهيج": "Samaheej",
  "سند": "Sanad",
  "شهركان": "Shahrakkan",
  "طشان": "Tashan",
  "عالي": "A'ali",
  "عراد": "Arad",
  "عسكر": "Askar",
  "عوالي": "Awali",
  "قلالي": "Galali",
  "كرانة": "Karranah",
  "كرباباد": "Karbabad",
  "كرزكان": "Karzakan",
  "مدينة حمد": "Hamad Town",
  "مدينة عيسى": "Isa Town",
  "مقابة": "Muqaba",
  "ميناء سلمان": "Mina Salman",
};
