// قاموس ترجمة التصنيفات (تصنيفات ومناطق) — مصدر واحد يستخدمه:
//  1) القوالب وقت البناء لطباعة البطاقات داخل HTML (مهم لمحركات البحث)
//  2) main.js بالمتصفح عبر TAGS_EN المولّد داخل ملف data.js
// كان مكرراً وينحرف — لا تضف ترجمة بأي مكان ثانٍ.
const AREAS = require("./areas.js");

module.exports = {
  // كل مناطق البحرين تأتي من areas.js — لا تكتب منطقة هنا يدوياً
  ...AREAS,

  "برجر": "Burger",
  "سندويشات": "Sandwiches",
  "وجبات سريعة": "Fast Food",
  "مخبز": "Bakery",
  "معجنات": "Pastries",
  "عراقي": "Iraqi",
  "مشاوي": "Grills",
  "ذرة": "Corn",
  "آلو وصوصات": "Fries & Sauces",
  "عيوش": "Aayosh",
  "شاورما": "Shawarma",
  "تركي": "Turkish",
  "بيتزا": "Pizza",
  "حلويات": "Sweets",
  "آيسكريم": "Ice Cream",
  "كيك": "Cakes",
  "هندي": "Indian",
  "إيطالي": "Italian",
  "آسيوي": "Asian",
  "مأكولات بحرية": "Seafood",
  "عربات طعام": "Food Trucks",
  "صحي": "Healthy",
  "كافيه": "Cafe",
  "مطعم عائلي": "Family Restaurant",
  "لبناني": "Lebanese",
  "إيراني": "Iranian",
  "بحريني": "Bahraini",
  "قهوة مختصة": "Specialty Coffee",
  "كرك": "Karak Tea",
  "مشروبات باردة": "Cold Drinks",
  "حلا ومعجنات": "Desserts & Pastries",
  "إفطار": "Breakfast",
  "مناسب للعمل والدراسة": "Good for Work/Study",
  "عائلي": "Family-Friendly",
  "تيك أواي": "Takeaway",
  "إلكترونيات": "Electronics",
  "المستلزمات المنزلية": "Home Essentials",
  "مستلزمات الهواتف": "Phone Accessories",
  "ملابس": "Clothing",
  "عناية وجمال": "Beauty & Care",
  "أطفال": "Kids",
  "كتب وقرطاسية": "Books & Stationery",
  "ديكور منزلي": "Home Decor",
  "ألعاب": "Toys",
  "إكسسوارات": "Accessories",
  "رياضة": "Sports",
  "مكتبة": "Library",
  "مشتل": "Nursery",
  "معدات التصوير واكسسوارته": "Photography Equipment",
  "كاميرات": "Cameras",
  "عدسات": "Lenses",
  "بصريات": "Optics",
  "مستلزمات السباكة": "Plumbing Supplies",
  "الكمبيوتر": "Computers",
  "تصحيح النصوص": "Proofreading",
  "تصميم": "Design",
  "ألوان": "Colors",
  "ترجمة": "Translation",
  "برمجة": "Coding",
  "مستندات": "Documents",
  "إنتاجية": "Productivity",
  "صور": "Photos",
  "أمان": "Security",
  "تعليم": "Education",
  "فيديو": "Video",
  "صوت": "Audio",
  "بيانات": "Data",
  "ذكاء اصطناعي": "AI",
  "شاطئ": "Beach",
  "إطلالة": "View",
  "تنزه": "Outing",
  "تاريخي": "Historic",
  "ترفيهي": "Entertainment",
  "طبيعة": "Nature",
  "دليل شامل": "Full Guide",
  "أفضل 10": "Top 10",
  "نهاية أسبوع": "Weekend",
  "نصائح": "Tips",
  "مواسم وفعاليات": "Seasons & Events",
  "نقل ومواصلات": "Transport",
  "ميزانية": "Budget",
  "للزوار": "For Visitors",
  "تقنية وبرمجيات": "Tech & Software",
  "تصميم ومونتاج": "Design & Editing",
  "تسويق وأعمال": "Marketing & Business",
  "مأكولات عالمية": "International Cuisine",
  "بروستد": "Broasted Chicken",
  "ممشى": "Walkway"
};
